"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Layout } from 'antd';
import AppHeader from '@/app/components/AppHeader'

const { Header, Content, Footer } = Layout;

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
      <body>
        <Layout>
          <Header style={{ background: "#fff", padding: "0 50px" }}>
            <AppHeader />
          </Header>
          <Content style={{ padding: "20px 50px", minHeight: "80vh" }}>
            {children}
          </Content>
          <Footer style={{ textAlign: "center" }}>
            © 2026 E-commerce
          </Footer>
        </Layout>
      </body>
    </html>
  );
}
